### ISSUE TITLE
ExM Function Reference

### ISSUE THREAD

**Issue by JnKTechstuff** [extendedmode/extendedmode#40]
Trying to pull money to return a value and compare it for purchasing will result in a table returned:

```
	local xPlayer = ExM.GetPlayerFromId(source)
	local money = xPlayer.getMoney
	if xPlayer and money >= thisItem.price then
```

Money returns this table:
```
### START TABLE ###
root
|-> __cfx_functionReference: "extendedmode:4670:17827"
### END TABLE ###
```

Which of course throws a table comparison error:
```
attempt to compare number with table
```

Running dev branch of ExM and latest artifact

**Comment by JnKTechstuff** [comment]
Function being called is:
```
	self.getMoney = function()
		return self.getAccount('money').money
	end
```

Which only returns a number normally (tested this).

**Comment by jaymo1011** [comment]
The problem is on line two: `local money = xPlayer.getMoney` you are not actually calling the function, you are just assigning the table `xPlayer.getMoney` (which when called, invokes the function reference) to `money`. To fix this, simply call the function like so: `local money = xPlayer.getMoney()`
